Sleep(500)
ControlFocus("Open","","ComboBox1")
Sleep(500)
ControlSetText("Open","","ComboBox1","C:\Testing\Tester\Competitive-tasks\MarsFramework\images.jpeg")
Sleep(500)
ControlClick("Open","","Button1")
Sleep(500)